184 general contact form
print4health/print4health pull request #216
Opened 2020-03-29 12:29 UTC by BoyPersoon

Hi Max,

Could you take a look at this!? My PHP is a bit rusty so let me know if you have any suggestions!
Also we would need some text in German, and in general at the top of the form to explain it's purpose.

2020-03-29 14:50 UTC, bartrail commented on src/Infrastructure/Controller/ContactController.php
> +            $email->to($params['email']);
```suggestion
            $email->to('contact@print4health.org');
            $email->cc($params['email']);
```
I would make it public that the email was sent to us and then is cc'ed to the sender too.

2020-03-29 14:51 UTC, bartrail commented on src/Infrastructure/Controller/ContactController.php
> +            $email->bcc("contact@print4health.org");
```suggestion
```

2020-03-31 12:04 UTC, bartrail commented
we had a discussion whether we should persist the contact form also in database for further processing. What do you think about it?

2020-03-31 19:46 UTC, BoyPersoon commented
I think we should prioritize getting the contact form online and add that functionality later (as a different issue).

Adding text on top of the form is more important right now I think.

2020-04-01 09:22 UTC, bartrail submitted a review, later dismissed

2020-04-01 09:22 UTC, bartrail commented on src/Domain/Contact/Mailer.php
> +    ) {
please add `string $from` as argument so we use the global .env variable (see the other mailer and the `services.yaml` for how to configure the env variables

2020-04-01 09:22 UTC, bartrail commented on src/Domain/Contact/Mailer.php
> +            ->from('contact@print4health.org')
the `$from` variable can then be used here

2020-04-01 09:30 UTC, gherkins requested changes
sorry, i meant to submit this earlier, but somehow didn't 🤔

2020-04-01 09:30 UTC, gherkins commented on .gitignore
> +/.idea
i think that would rather belong in your local `.git/info/exclude`

2020-04-01 09:30 UTC, gherkins commented on assets/js/app.js
> +                    <li className="nav-item">
we need to doublecheck that theres enough space left in the main-navbar

maybe move this to the footer? @bartrail

2020-04-01 09:30 UTC, gherkins commented on src/Infrastructure/Controller/ContactController.php
> +
@bartrail  shouldn't we add more server-side validation, as in the registration form?

2020-04-03 10:46 UTC, gherkins approved these changes

2020-04-03 10:46 UTC, merged